// data.js for Workout Recommender
export const data = {
  options: [
    {
      name: 'Bodyweight Squats',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
      image: 'images/squats.svg',
    },
    {
      name: 'Jumping Jacks',
      type: 'Cardio',
      targetArea: 'Full Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
      image: 'images/jumping-jacks.svg',
    },
    {
      name: 'Push-Ups',
      type: 'Strength',
      targetArea: 'Upper Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
      image: 'images/pushups.svg',
    },
    {
      name: 'Dumbbell Lunges',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'Dumbbells',
      durationMinutes: 30,
      difficulty: 'Intermediate',
      image: 'images/lunges.svg',
    },
    {
      name: 'Mountain Climbers',
      type: 'HIIT',
      targetArea: 'Core',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Intermediate',
      image: 'images/mountain-climbers.svg',
    },
    {
      name: 'Plank',
      type: 'Strength',
      targetArea: 'Core',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
      image: 'images/plank.svg',
    },
    {
      name: 'Resistance Band Rows',
      type: 'Strength',
      targetArea: 'Upper Body',
      equipment: 'Resistance Bands',
      durationMinutes: 30,
      difficulty: 'Intermediate',
      image: 'images/band-rows.svg',
    },
    {
      name: 'Kettlebell Swings',
      type: 'HIIT',
      targetArea: 'Full Body',
      equipment: 'Kettlebell',
      durationMinutes: 30,
      difficulty: 'Advanced',
      image: 'images/kettlebell-swings.svg',
    },
    {
      name: 'Yoga Sun Salutation',
      type: 'Flexibility',
      targetArea: 'Full Body',
      equipment: 'No Equipment',
      durationMinutes: 30,
      difficulty: 'Beginner',
      image: 'images/sun-salutation.svg',
    },
    {
      name: 'Burpees',
      type: 'HIIT',
      targetArea: 'Full Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Advanced',
      image: 'images/burpees.svg',
    },
    {
      name: 'Dumbbell Shoulder Press',
      type: 'Strength',
      targetArea: 'Upper Body',
      equipment: 'Dumbbells',
      durationMinutes: 30,
      difficulty: 'Intermediate',
      image: 'images/shoulder-press.svg',
    },
    {
      name: 'Hamstring Stretch',
      type: 'Flexibility',
      targetArea: 'Lower Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
      image: 'images/hamstring-stretch.svg',
    },
    {
      name: 'Russian Twists',
      type: 'Strength',
      targetArea: 'Core',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Intermediate',
      image: 'images/russian-twists.svg',
    },
    {
      name: 'Resistance Band Squats',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'Resistance Bands',
      durationMinutes: 30,
      difficulty: 'Intermediate',
      image: 'images/band-squats.svg',
    },
    {
      name: 'Kettlebell Deadlift',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'Kettlebell',
      durationMinutes: 45,
      difficulty: 'Advanced',
      image: 'images/kettlebell-deadlift.svg',
    },
  ],
};
