// data.js for Workout Recommender
export const data = {
  options: [
    {
      name: 'Bodyweight Squats',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
    },
    {
      name: 'Jumping Jacks',
      type: 'Cardio',
      targetArea: 'Full Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
    },
    {
      name: 'Push-Ups',
      type: 'Strength',
      targetArea: 'Upper Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
    },
    {
      name: 'Dumbbell Lunges',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'Dumbbells',
      durationMinutes: 30,
      difficulty: 'Intermediate',
    },
    {
      name: 'Mountain Climbers',
      type: 'HIIT',
      targetArea: 'Core',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Intermediate',
    },
    {
      name: 'Plank',
      type: 'Strength',
      targetArea: 'Core',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
    },
    {
      name: 'Resistance Band Rows',
      type: 'Strength',
      targetArea: 'Upper Body',
      equipment: 'Resistance Bands',
      durationMinutes: 30,
      difficulty: 'Intermediate',
    },
    {
      name: 'Kettlebell Swings',
      type: 'HIIT',
      targetArea: 'Full Body',
      equipment: 'Kettlebell',
      durationMinutes: 30,
      difficulty: 'Advanced',
    },
    {
      name: 'Yoga Sun Salutation',
      type: 'Flexibility',
      targetArea: 'Full Body',
      equipment: 'No Equipment',
      durationMinutes: 30,
      difficulty: 'Beginner',
    },
    {
      name: 'Burpees',
      type: 'HIIT',
      targetArea: 'Full Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Advanced',
    },
    {
      name: 'Dumbbell Shoulder Press',
      type: 'Strength',
      targetArea: 'Upper Body',
      equipment: 'Dumbbells',
      durationMinutes: 30,
      difficulty: 'Intermediate',
    },
    {
      name: 'Hamstring Stretch',
      type: 'Flexibility',
      targetArea: 'Lower Body',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Beginner',
    },
    {
      name: 'Russian Twists',
      type: 'Strength',
      targetArea: 'Core',
      equipment: 'No Equipment',
      durationMinutes: 15,
      difficulty: 'Intermediate',
    },
    {
      name: 'Resistance Band Squats',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'Resistance Bands',
      durationMinutes: 30,
      difficulty: 'Intermediate',
    },
    {
      name: 'Kettlebell Deadlift',
      type: 'Strength',
      targetArea: 'Lower Body',
      equipment: 'Kettlebell',
      durationMinutes: 45,
      difficulty: 'Advanced',
    },
  ],
};
